basePath: /
definitions:
  accountgrp.CreateAccountRequest:
    properties:
      currency:
        type: string
      name:
        type: string
    required:
    - currency
    - name
    type: object
  accountgrp.CreateAccountResponse:
    properties:
      data:
        $ref: '#/definitions/db_generated.Account'
    type: object
  accountgrp.GetAccountResponse:
    properties:
      data:
        $ref: '#/definitions/db_generated.Account'
    type: object
  accountgrp.ListAllAccountsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/db_generated.Account'
        type: array
    type: object
  accountgrp.SearchAccountsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/db_generated.Account'
        type: array
    type: object
  accountgrp.UpdateRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  accountgrp.UpdateResponse:
    properties:
      data:
        $ref: '#/definitions/db_generated.Account'
    type: object
  db_generated.Account:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      name:
        type: string
      owner:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: qiushi.yann@gmail.com
    name: Qiushi Yan
    url: github.com/qiushiyan/simplebank/issues
  description: Example API for a banking system, see development notes at https://github.com/qiushiyan/simplebank
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: SimpleBank API
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: List accounts for the authenticated user in the token
      parameters:
      - description: page id, default to 1
        in: query
        name: page_id
        type: integer
      - description: page size, default to 5
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db_generated.Account'
            type: array
        "401":
          description: Unauthorized
        "409":
          description: Conflict
      security:
      - Bearer: []
      summary: List accounts for user
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: Get account by id, token should match account owner
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accountgrp.GetAccountResponse'
        "401":
          description: Unauthorized
        "409":
          description: Conflict
      security:
      - Bearer: []
      summary: Get an account
      tags:
      - accounts
    patch:
      consumes:
      - application/json
      description: Update account by id, token should match account owner, currently
        only name can be updated
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/accountgrp.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accountgrp.UpdateResponse'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      security:
      - Bearer: []
      summary: Update an account
      tags:
      - accounts
  /accounts/all:
    get:
      consumes:
      - application/json
      description: list all accounts, available only to admin
      parameters:
      - description: page id, default to 1
        in: query
        name: page_id
        type: integer
      - description: page size, default to 50
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/accountgrp.ListAllAccountsResponse'
            type: array
        "401":
          description: Unauthorized
        "409":
          description: Conflict
      security:
      - Bearer: []
      summary: List all accounts
      tags:
      - accounts
  /accounts/create:
    post:
      consumes:
      - application/json
      description: Create an account with the given name and currency. Currency should
        be one of "USD", "EUR" or "CAD". Name-Currency combination should be unique.
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/accountgrp.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accountgrp.CreateAccountResponse'
        "400":
          description: Bad Request
        "409":
          description: Conflict
      security:
      - Bearer: []
      summary: Create an account
      tags:
      - accounts
  /accounts/search:
    get:
      consumes:
      - application/json
      description: Search accounts by owner
      parameters:
      - description: owner name
        in: query
        name: owner
        required: true
        type: string
      - description: page id, default to 1
        in: query
        name: page_id
        type: integer
      - description: page size, default to 10
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accountgrp.SearchAccountsResponse'
        "400":
          description: Bad Request
        "409":
          description: Conflict
      security:
      - Bearer: []
      summary: Search accounts
      tags:
      - accounts
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
