version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  init-db:
    image: backend
    command: ./migrate
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_started

  backend:
    image: backend
    build:
      context: .
      dockerfile: zarf/docker/dockerfile.bank-api
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/bank
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: zarf/docker/dockerfile.frontend
    environment:
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=secret
      - API_URL=http://backend:3000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=testtest
      - USER_USERNAME=user
      - USER_PASSWORD=testtest
    ports:
      - "3001:3001"
    depends_on:
      init-db:
        condition: service_completed_successfully
      backend:
        condition: service_started

volumes:
  postgres_data:
