apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  namespace: simplebank

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api

  template:
    metadata:
      labels:
        app: bank-api
    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: bank-api
          image: bank-api-image

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

          ports:
            - name: bank-api
              containerPort: 3000
            - name: bank-api-debug
              containerPort: 4000

          # readinessProbe: # readiness probes mark the service available to accept traffic.
          #   httpGet:
          #     path: /debug/readiness
          #     port: 4000
          #   initialDelaySeconds: 2
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 2

          # livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          #   httpGet:
          #     path: /debug/liveness
          #     port: 4000
          #   initialDelaySeconds: 2
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 2
