apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  namespace: simplebank
spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: bank-api
          resources:
            requests:
              cpu: "1500m" # I need access to 1/2 core on the node.
            limits:
              cpu: "1500m" # Execute instructions 50ms/100ms on my 1 core.
