apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/bank-api/
patches:
  - path: ./dev-deployment-patch.yaml
  - path: ./dev-service-patch.yaml
images:
  - name: bank-api-image
    newName: qiushiyan/simplebank/bank-api
    newTag: 0.0.1
